# Generated by Django 5.0.6 on 2024-07-11 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_commande'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='total',
            field=models.CharField(default=500, max_length=150),
            preserve_default=False,
        ),
    ]
